"""Initial migration.

Revision ID: 043c0356f9c8
Revises: 9afc1abc74ca
Create Date: 2023-09-10 23:31:39.258966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043c0356f9c8'
down_revision = '9afc1abc74ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.Column('sub_place', sa.Text(), nullable=True),
    sa.Column('sub_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sub')
    # ### end Alembic commands ###
