"""Initial migration.

Revision ID: 9afc1abc74ca
Revises: 9d5e44800aac
Create Date: 2023-09-08 22:44:51.565922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9afc1abc74ca'
down_revision = '9d5e44800aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dean', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dean', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
