"""Initial migration.

Revision ID: 9d5e44800aac
Revises: 5463df5ad7b2
Create Date: 2023-09-08 22:37:26.582873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5e44800aac'
down_revision = '5463df5ad7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dean', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_place', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dean', schema=None) as batch_op:
        batch_op.drop_column('from_place')

    # ### end Alembic commands ###
