"""Initial migration.

Revision ID: f98d501c1498
Revises: 043c0356f9c8
Create Date: 2023-09-11 15:00:25.733819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98d501c1498'
down_revision = '043c0356f9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fs_app_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_access_token', sa.Text(), nullable=True),
    sa.Column('token_expires', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('user_sub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_open_id', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('user_open_id_ts', sa.Integer(), nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.TEXT(), nullable=True))
        batch_op.drop_column('user_open_id_ts')
        batch_op.drop_column('user_open_id')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_phone')

    op.drop_table('fs_app_info')
    # ### end Alembic commands ###
